### PR TITLE
fix: allow parallel sendTransfer calls

### PR DESCRIPTION
**Pull request by michielbdejong**
Without this, if you send a few transfers at once, the second and further ones will fail because they will all try to use the same sequence number. Once you've started preparing an escrow, it's necessary to queue up the other transfers until the first one has been signed and fully submitted.

### CODE REVIEW

**Comment by sharafian** [comment]
We could use a chained promise for this, which could be simpler and more elegant because it uses nodes event queue for all the queueing. It's the construct that plugin virtual uses to make sure balance updates go through in the right order: https://github.com/interledgerjs/ilp-plugin-virtual/blob/master/src/model/balance.js#L32

**Comment by emschwartz** [comment]
What's the status of this?

**Comment by michielbdejong** [comment]
I'll rewrite it the way Ben suggested, and then re-request his review. It's one of several things I've fixed for the testnet, created PRs for, but haven't fully shepherded through review yet because of other higher priorities.

**Review by sharafian — APPROVED** [review]

**Comment by michielbdejong** [comment]
Thanks! can you do the merge?

**Pull request merged**
